name: First Demo Action

# event
on:
  push:
    branches:
      - main

# job
jobs:
  demo-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: List files
        run: ls -la ${{ github.workspace }}