name: First Demo Action

# event
on:
  push:
    branches:
      - main

# job
jobs:
  demo-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Action Started"
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run a one line script
        run: echo "Hello World!"
      - name: Run a multi line script
        run: |
          echo "First line"
          echo "Second line"
      - name: List files
        run: ls ${{ github.workspace }}
      - name: Print github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Action completed
        run: echo "Action Completed"